### ISSUE TITLE
MongoError: $where is not allowed in this context

### ISSUE THREAD

**Issue by lincolnthree** [aravindnc/mongoose-paginate-v2#120]
**Describe the bug**
```
MongoError: $where is not allowed in this context
        at MessageStream.messageHandler (/Users/lincoln/projects/maritlabs/topdecked-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:268:20)
        at MessageStream.emit (events.js:315:20)
        at processIncomingData (/Users/lincoln/projects/maritlabs/topdecked-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
        at MessageStream._write (/Users/lincoln/projects/maritlabs/topdecked-api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
        at writeOrBuffer (_stream_writable.js:352:12)
        at MessageStream.Writable.write (_stream_writable.js:303:10)
        at Socket.ondata (_stream_readable.js:719:22)
        at Socket.emit (events.js:315:20)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:284:9)
        at Socket.Readable.push (_stream_readable.js:223:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
      ok: 0,
      code: 2,
      codeName: 'BadValue'
    }

```

QUERY:
```
{
      source: 'user',
      format: { '$in': [ 'text', 'json' ] },
      '$and': [
        { '$where': 'this.comments.length >= 60' },
        { '$where': 'this.comments.length <= 100' },
        { '$where': 'this.tags.length <= 15' }
      ]
    }
```

**To Reproduce**
Run the query on a PaginateModel:

```
await PostModel.paginate(query, {
            offset: page * limit,
            lean: true,
            leanWithId: false,
            limit,
            sort: { created: -1 }
          })
```

**Expected behavior**
Should not throw an error. Results should be returned.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: NA
 - Version 1.3.14

**Comment by aravindnc** [comment]
@lincolnthree Sorry $where is not supported as mentioned in the readme
https://github.com/aravindnc/mongoose-paginate-v2#note

**Comment by lincolnthree** [comment]
My apologies! I should have seen that. Thank you for the response!
